version: "3.9"
services:
  backend:
    build: ./backend
    container_name: muse-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data/cache:/app/data/cache
      - ./backend/data/models:/app/data/models
    environment:
      - ENV=production

  frontend:
    build: ./frontend
    container_name: muse-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm run dev
